# Generated by Django 4.0.1 on 2022-01-20 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='email',
        ),
    ]
