# Generated by Django 4.0.1 on 2022-01-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_files_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='matchingcode',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
