# Generated by Django 4.0.1 on 2022-01-24 04:18

from django.db import migrations
import djongo.models.fields
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_files_matchingcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='matchingcode',
            field=djongo.models.fields.ArrayField(default=[], model_container=main.models.match),
        ),
    ]
